### ISSUE TITLE
Attribution bug

### ISSUE THREAD

**Issue by acalcutt** [prozessor13/maplibre-gl-js#36]
Just wanted to let you know that since the last merge with master, the terrain3d branch has this attribution bug ( https://github.com/maplibre/maplibre-gl-js/issues/640 ) . I tested the upstream fix in my local copy and it works for me.

Other than that I wanted to comment that the 3d terrain has been working pretty well. My [wifidb.net map](https://wifidb.net/wifidb/opt/map.php?func=wifidbmap&labeled=0) is using the latest (https://github.com/prozessor13/maplibre-gl-js/commit/ab0d337b39229b202acb50b9e913b4e5f95f91ca)  with the fixes to attribution and I haven't had to many issues (except when i ran it on an older laptop...haha)

**Comment by prozessor13** [comment]
I merged now the current main branch and i hope this will fix your issue. If yes please close the bugreport. Thx.

**Comment by acalcutt** [comment]
I tested this, and this does seem to fix attribution. However there seems to be another issue that seems to have been introduced in ( https://github.com/prozessor13/maplibre-gl-js/commit/4c4ff8fa45bcdb725d400dc2f0b6efcd2b362dbe )

When my map loads, without terrain, everything loads properly. I then addTerrain and it still looks right. However when I removeTerrain the map loses most of its features and I only see the color background like this
![fill_issue](https://user-images.githubusercontent.com/3792408/143613524-c366c147-2c2b-48e9-8d78-c7a1de1419d5.png)


I have tested going back to the ( https://github.com/prozessor13/maplibre-gl-js/commit/ab0d337b39229b202acb50b9e913b4e5f95f91ca ) commit, re-adding the attibution fixes and the label cluster bugfix you did for me, and that all works. However if I do the same with ( https://github.com/prozessor13/maplibre-gl-js/commit/4c4ff8fa45bcdb725d400dc2f0b6efcd2b362dbe ), the bug appears.

**Comment by prozessor13** [comment]
I hope it is working again now!

**Comment by acalcutt** [comment]
Thanks, I'll give it a try later today. I actually found the attribution on master is still not working right and updated my bug report in  ( https://github.com/maplibre/maplibre-gl-js/issues/640 ). At the moment I have been manually replacing attribution_control.ts with the one from September, before they started messing with it ( https://github.com/prozessor13/maplibre-gl-js/blob/7149e8ac2fe6db1ea3641f40139b234b4be3b4e8/src/ui/control/attribution_control.ts ), which works fine.

**Comment by acalcutt** [comment]
I tested the fix for ( https://github.com/prozessor13/maplibre-gl-js/issues/36#issuecomment-980163511 ) and it seemed to work.

I'm still reverting attribution_control.ts since the one on master is still bugged for me (even with their new fixes today).

**Comment by acalcutt** [comment]
Closing this since the latest merge from main contained the attribution fixes
